version: "3"

services:
  core:
    build: /home/lars/code/klms/kloudstrapbash
    image: core
    environment:
      SPRING_APPLICATION_JSON: '{"spring.datasource": {"url": "jdbc:mysql://db:3306/kms?useSSL=false", "password": "kloudfile"}}'
    ports:
      - 8083:8083
  db:
    environment:
      MYSQL_ROOT_PASSWORD: kloudfile
      MYSQL_DATABASE: kms
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/cnf:/etc/mysql/conf.d
      - ./mysql/log:/var/log/mysql
